stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - cd $DEPLOY_DIR_STAGING
    - git remote set-url origin http://${GIT_USER}:${GIT_TOKEN}@git.mediaciptainformasi.co.id/yosuamalau/puskesmas-be.git
    - git pull origin main
    - if git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -q composer.json; then docker run --rm -v "$PWD:/app" -w /app composer:2 sh -c "git config --global --add safe.directory /app && composer install --no-dev --optimize-autoloader --no-blocking --ignore-platform-reqs"; fi
    - docker compose -f docker-compose.yml build
    - docker compose -f docker-compose.yml up -d
