[supervisord]
nodaemon=true
user=app
logfile=/var/log/supervisord/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=warn

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F -R
autostart=true
autorestart=true
priority=5
stdout_logfile=/var/log/supervisord/php-fpm-stdout.log
stderr_logfile=/var/log/supervisord/php-fpm-stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisord/nginx-stdout.log
stderr_logfile=/var/log/supervisord/nginx-stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
